feat: add functionality to contact form
Frachtwerk/essencium-frontend pull request #392
Opened 2023-09-15 13:48 UTC by CathrinTruchan

In this PR the functionality for the contact form has been added. 
The user can now send a message to a given email address over the `ContactView`.

2023-09-19 18:03 UTC, CathrinTruchan commented
> After submitting, the form should be cleared. Otherwise, good job! 🚀

The form is now cleared after submitting and I added a custom notification message. @qhantom please check again 🚀

2023-09-20 05:51 UTC, qhantom requested changes
I'd like to adjust it a tiny bit. If the user clicks on the submit button, the form gets cleared immediately instead of waiting for the request to be settled. Maybe the request fails and another one will make it but the form needs to be refilled again by the user. Another point is [to work with the loading state of the button](https://v6.mantine.dev/core/button/#loading-state) dependent of the request. The loading state topic could be outsourced into a separate issue since there are several locations where we need to implement it. Could you write that issue please?

2023-09-20 07:43 UTC, CathrinTruchan commented
> I'd like to adjust it a tiny bit. If the user clicks on the submit button, the form gets cleared immediately instead of waiting for the request to be settled. Maybe the request fails and another one will make it but the form needs to be refilled again by the user. Another point is [to work with the loading state of the button](https://v6.mantine.dev/core/button/#loading-state) dependent of the request. The loading state topic could be outsourced into a separate issue since there are several locations where we need to implement it. Could you write that issue please?

Good point :) the form is now cleared onSuccess.You can have another look :)
I will write a issue for the loading state topic ;)

2023-09-20 08:16 UTC, qhantom approved these changes

2023-09-20 08:17 UTC, merged