613 migration to nextjs app router
Frachtwerk/essencium-frontend pull request #615
Opened 2024-08-09 12:48 UTC by PhilKsr

## DESCRIPTION

This PR contains the migration from next.js pages router to app router.
It breaks down to following changes and follows the [migrationguide](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app)
- replace _document.tsx and _app.tsx with layout.tsx
- outsource and reorganize providers
- replace next/router with next/navigation and replace used router functionality with new api
- replace next-i18next with react-i18next to migrate translations
- replace all index.tsx with page.tsx
- outsource client side components to own files to prepare refactoring

Whats missing?
- overall refactoring concerning server and client side functionality and components
- refactoring of TranslationView.tsx (several bugs in there)
- adjustments to hot reload app on language change 
- documentation (will follow after technical review)

### TO-DO

- [x] implement and update tests
- [ ] update docs
- [ ] pull `main` & resolve merge conflicts
- [ ] check Vercel deployment

### CLOSES

closes #613

2024-08-09 13:12 UTC, PhilKsr commented
@qhantom nx causes errors during linting. Would you have a quick look what could be the error and start a review afterwards? 🐳

2024-08-09 15:46 UTC, qhantom requested changes
When building the app, I get the following error:

![image](https://github.com/user-attachments/assets/3a52006c-1a2a-4eab-9df9-49dd677bc3a2)

2024-08-09 15:46 UTC, qhantom commented on packages/app/package.json
>      "next-i18next": "15.3.0",
Can this be removed since we only need `react-i18next`?

2024-08-09 15:46 UTC, qhantom commented on packages/app/src/app/[locale]/(main)/layout.tsx
It saw that the current nav item is no longer highlighted when on a route and the language is set to german

![image](https://github.com/user-attachments/assets/c5576fb1-696a-4afd-bb12-41cd0ef9a44e)

2024-08-09 15:48 UTC, qhantom commented
> @qhantom nx causes errors during linting. Would you have a quick look what could be the error and start a review afterwards? 🐳

You can just check it locally by building the app on your system. The linting is executed than and throws the same error(s) as nx does

2024-08-09 15:49 UTC, qhantom commented
For some reason, the logo at the upper left corner is flickering on route change, could you reproduce that?

2024-08-12 11:48 UTC, PhilKsr commented on packages/app/src/app/[locale]/(main)/layout.tsx
Thats something we have to fix in the lib in another PR, just like changing the locale. 
I will create a ticket for that. 👍🏼

2024-08-12 11:51 UTC, PhilKsr commented
> For some reason, the logo at the upper left corner is flickering on route change, could you reproduce that?

Not really. If you mean the unexpected fold in Home component - thats also something for the lib.

2024-09-09 15:33 UTC, qhantom approved these changes
Nice one! Fits, wiggles and has air.

2024-09-09 15:33 UTC, qhantom commented on packages/app/src/app/[locale]/(main)/layout.tsx
> +      <AuthLayout>{children} </AuthLayout>
One space bro 🤜

2024-09-10 11:46 UTC, merged

2024-10-15 11:41 UTC, CathrinTruchan reviewed
Nice 👯